### PR TITLE
Marlin Update

### PR DESCRIPTION
**Pull request by mike391**
The purpose of this is to update the Labists ET4 changes to the latest Marlin ET4 changes.

I rebased Atanasovgoran/Marlin-Labists-ET4  onto davidtgbe/Marlin mainbranch and resolved all the conflicts (nothing serious).  However I dont have a flash tool on me right now, while this theoretically should work, id love your opinion on if I made any breaking changes @Atanasovgoran

### CODE REVIEW

**Comment by Atanasovgoran** [comment]
> The purpose of this is to update the Labists ET4 changes to the latest Marlin ET4 changes.
> 
> I rebased Atanasovgoran/Marlin-Labists-ET4 onto davidtgbe/Marlin mainbranch and resolved all the conflicts (nothing serious). However I dont have a flash tool on me right now, while this theoretically should work, id love your opinion on if I made any breaking changes @Atanasovgoran

Unfortunately I have upgraded my printer with an SKR. So I can't test it.
I still have the board, I could try hooking motors and a hotend to test it if they work, and maybe run some gcode without it being on a printer. But no promises, since i am not even sure where i left the board. Maybe if someone else has the printer they could test it.

Do you have any arduinos laying around? I think you can use the arduino to flash the mainboard.

**Comment by mike391** [comment]
I do actually, good thinking. I'll try to get that setup sometime this week
to test it out!

**Comment by mike391** [comment]
Actually, I have your previous build running on my printer currently. If I
upgrade to my changes and it bricks it, do you know if I can flash your
previous version using the sdcard in dfu?

**Comment by zavorra** [comment]
> Do you have any arduinos laying around? I think you can use the arduino to flash the mainboard.

Interesting, do you have some tutorial or some other pointer on that?

**Comment by Atanasovgoran** [comment]
> > Do you have any arduinos laying around? I think you can use the arduino to flash the mainboard.
> 
> Interesting, do you have some tutorial or some other pointer on that?

Well, for the Stm32 apparently not.

But aparently the STM32CubeProg can program STMs over UART, USB DFU, I2C, SPI, and CAN.

So depending on how the usb interface is implemented, it could be used for programming it. But i think the boot0 and boot1 pins need to be pullep up to 3.3V


https://www.st.com/en/development-tools/stm32cubeprog.html

**Comment by Atanasovgoran** [comment]
> > Do you have any arduinos laying around? I think you can use the arduino to flash the mainboard.
> 
> Interesting, do you have some tutorial or some other pointer on that?

USB_USART1_TX => PA9
USB_USART1_RX => PA10

According to the datasheet these pins can be used for that.

Boot0 is on pin 94 lqfp100
And pin 60 on the lqfp64

Boot1 is on PB2 and that is on one of the lcd connectors, which makes it easy to access
P1_3_TOUCH_15_/CS => PB2

Also the same lcd connector has a convenient 3.3V

**Comment by manotroll** [comment]
possible support for et5 with noisy drivers?

**Comment by deftdawg** [comment]
This PR builds and flashes fine, there's no change to the about screen though.  

~~Question how does one use the Labists's Auto Bed Leveling in this firmware?~~ Neverind, I need to go read up on UBL
 
Flash using the following:
```
deftdawg @Deftdawgs-MacBook-Pro ~/source/Marlin-Labists-ET4/.pio/build/ET4  [ bugfix-2.0.x ]
$ /usr/local/Cellar/stlink/1.7.0/bin/st-flash write firmware.bin 0x08010000
st-flash 1.7.0
2022-04-16T23:43:35 INFO common.c: F4xx: 192 KiB SRAM, 1024 KiB flash in at least 16 KiB pages.
file firmware.bin md5 checksum: e9843bfcc819ef317aac3e0c29a8e, stlink checksum: 0x02c2c86e
2022-04-16T23:43:35 INFO common.c: Attempting to write 410636 (0x6440c) bytes to stm32 address: 134283264 (0x8010000)
EraseFlash - Sector:0x4 Size:0x10000 2022-04-16T23:43:36 INFO common.c: Flash page at addr: 0x08010000 erased
EraseFlash - Sector:0x5 Size:0x20000 2022-04-16T23:43:38 INFO common.c: Flash page at addr: 0x08020000 erased
EraseFlash - Sector:0x6 Size:0x20000 2022-04-16T23:43:40 INFO common.c: Flash page at addr: 0x08040000 erased
EraseFlash - Sector:0x7 Size:0x20000 2022-04-16T23:43:42 INFO common.c: Flash page at addr: 0x08060000 erased
2022-04-16T23:43:42 INFO common.c: Finished erasing 4 pages of 131072 (0x20000) bytes
2022-04-16T23:43:42 INFO common.c: Starting Flash write for F2/F4/F7/L4
2022-04-16T23:43:42 INFO flash_loader.c: Successfully loaded flash loader in sram
2022-04-16T23:43:42 INFO flash_loader.c: Clear DFSR
2022-04-16T23:43:42 INFO common.c: enabling 32-bit flash writes
2022-04-16T23:43:48 INFO common.c: Starting verification of write complete
2022-04-16T23:43:51 INFO common.c: Flash written and verified! jolly good!
```

**Comment by deftdawg** [comment]
The PR is good, merge it.

**Pull request merged**
